apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        rewrite {
          name regex test.example.com test.default.svc.cluster.local
          answer name test.default.svc.cluster.local test.example.com
        }

        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
