apiVersion: v1
kind: Service
metadata:
  name: sonarqube-sonarqube
  namespace: ci
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    app: sonarqube
    release: sonarqube
  type: ClusterIP
